### ISSUE TITLE
Disable SSL verification in LWP

### ISSUE THREAD

**Issue by CaledoniaProject** [Dudley5000/WWW-Shodan-API#1]
I had to disable ssl verification when creating LWP

ssl_opts => { verify_hostname => 0, SSL_verify_mode => 'SSL_VERIFY_NONE' }

maybe it should be merged into your code.

**Comment by reyjrar** [comment]
Probably not a good idea to disable SSL verification.  That sounds like your request is being man-in-the-middled or your system trust anchors are not setup properly.

If you want to disable it for your script you can use environment variables:

```
PERL_LWP_SSL_VERIFY_HOSTNAME=0
```

Though, it'd be better to set your CA file or directory variables to where your trusted CA's are:

```
HTTPS_CA_FILE=/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem
HTTPS_CA_DIR=/etc/pki/ca-trust/extracted/pem
```

If you have to set verify none on a publicly accessible HTTPS API, you should be *very* concerned about the integrity of the data you are sending/receiving.
